name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "build/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-26.04
    env:
      TOOLS: "${{github.workspace}}/build/tools"
      TOOLS_LOCAL: "${{github.workspace}}/build/tools/local"
      PIPX_HOME: "${{github.workspace}}/build/tools/python"
      PIPX_BIN_DIR: "${{github.workspace}}/build/tools/python/bin"
    steps:
      - uses: actions/checkout@v5

      - name: 'Tooling: Install Tools from Distribution'
        run: |
          set -e;
          sudo apt-get -q -y update;
          sudo apt-get -q -y install \
            cmake \
            curl \
            fpga-icestorm \
            fpga-icestorm-chipdb \
            git \
            gfortran \
            gperf \
            haskell-stack \
            iverilog \
            libboost-dev \
            libboost-iostreams-dev \
            libboost-program-options-dev \
            libboost-thread-dev \
            libeigen3-dev \
            pipx \
            rsync \
            yosys \
            yosys-abc;

          npm install -g --ignore-scripts wavedrom;

      - name: 'Tooling: Restore from Cache'
        id: cache-build-tools-restore
        uses: actions/cache/restore@v6
        with:
          path: ${{github.workspace}}/build/tools
          key: ${{runner.os}}-build-tools

      - name: 'Tooling: Download and Install Project Apicula (Gowin FPGAs)'
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        run: |
          set -e;
          mkdir -p "${PIPX_HOME}" && pushd "${PIPX_HOME}";

          pipx install --system-site-packages --force apycula;

          popd;

      - name: 'Tooling: Download and Install SBY'
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        run: |
          set -e;
          mkdir -p "${TOOLS}" && pushd "${TOOLS}";
          . "${PIPX_HOME}/venvs/apycula/bin/activate";

          git clone https://github.com/SRI-CSL/yices2.git;
          pushd yices2;
          autoconf;
          ./configure --prefix="${TOOLS_LOCAL}" --exec-prefix="${TOOLS_LOCAL}";
          make && make install;
          popd;

          git clone https://github.com/YosysHQ/sby.git;
          pushd sby;
          make && make install PREFIX="${TOOLS_LOCAL}";
          popd;

          popd;

      - name: 'Tooling: Download and Install SV2V'
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        run: |
          set -e;
          pushd "${TOOLS}";

          git clone https://github.com/zachjs/sv2v.git;
          pushd sv2v && make && popd;

          popd;

      - name: 'Tooling: Download and Install Project X-Ray (Xilinx FPGAs)'
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        run: |
          pushd "${TOOLS}";
          . "${PIPX_HOME}/venvs/apycula/bin/activate";

          git clone https://github.com/f4pga/prjxray.git;
          git clone https://github.com/f4pga/prjxray-db.git;

          pushd prjxray;
          CMAKE_POLICY_VERSION_MINIMUM=3.5 CXXFLAGS="-std=c++20" make build;
          python -m pip install --prefix "${TOOLS}/python" -r requirements.txt;
          popd;

          popd;

      - name: 'Tooling: Download, Build and Install nextpnr'
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        run: |
          set -e;
          pushd "${TOOLS}";
          . "${PIPX_HOME}/venvs/apycula/bin/activate";

          git clone https://github.com/YosysHQ/nextpnr.git;

          mkdir -p nextpnr/build && pushd nextpnr;
          git submodule update --init --recursive;

          cd build;
          cmake .. \
            -DARCH="ice40;himbaechel" \
            -DHIMBAECHEL_UARCH="gowin;xilinx" \
            -DICESTORM_INSTALL_PREFIX=/usr \
            -DICEBOX_DATADIR=/usr/share/fpga-icestorm/chipdb \
            -DHIMBAECHEL_PRJXRAY_DB="${TOOLS}/prjxray-db" \
            -DCMAKE_INSTALL_PREFIX="${TOOLS_LOCAL}";

          make -j$(nproc) && make install;
          popd;

          popd;

      - name: 'Tooling: Download and Install mdBook'
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        run: |
          set -e;
          pushd "${TOOLS}";

          mkdir -p mdbook;
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.5.3/mdbook-v0.5.3-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=mdbook;

          popd;

      - name: 'Tooling: Store in Cache'
        id: cache-build-tools-store
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v6
        with:
          path: ${{github.workspace}}/build/tools
          key: ${{steps.cache-build-tools-restore.outputs.cache-primary-key}}

      - name: 'Test, Synthesise, Place-and-Route, Pack Bitstream and Generate Documentation'
        run: |
          set -e;
          pushd "${GITHUB_WORKSPACE}/build";
          export PYTHON_VENV="${PIPX_HOME}/venvs/apycula/bin/activate";
          export PATH="${TOOLS_LOCAL}/bin:${TOOLS}/sv2v/bin:${TOOLS}/mdbook:${PATH}";
          . "${PYTHON_VENV}";

          mkdir -p out;
          tar -czv "${PIPX_HOME}/venvs/apycula" > out/apicula-venv.tar.gz;

          MAKE="make all NEXTPNR_PREFIX=${TOOLS_LOCAL}/bin/ PYTHON_VENV=${PYTHON_VENV}";
          make --version;

          ICE40_MAKE="${MAKE}";
          ${ICE40_MAKE} SYNTH_TARGET=ice40up5k PNR_PACKAGE=sg48;
          ${ICE40_MAKE} SYNTH_TARGET=ice40hx1k PNR_PACKAGE=tq144;

          GOWIN_MAKE="${MAKE} GOWIN_PACK=${PIPX_BIN_DIR}/gowin_pack";
          ${GOWIN_MAKE} SYNTH_TARGET=gw2alv18 PNR_PACKAGE=pg256 GOWIN_SPEED_GRADE=C8/I7;

          XILINX_MAKE="${MAKE} PROJECT_XRAY_PATH=${TOOLS}/prjxray";
          ${XILINX_MAKE} SYNTH_TARGET=xc7a35t PNR_PACKAGE=fgg484 XILINX_SPEED_GRADE=2;

          popd;

      - name: 'Bundle Artefacts'
        if: always()
        run: |
          set -e;
          pushd "${GITHUB_WORKSPACE}/build";
          GZIP_OPT=-9 tar -cz out > fpga-sv-template-out.tar.gz;
          popd;

      - name: 'Store Artefacts'
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: fpga-sv-template-out
          if-no-files-found: error
          archive: false
          path: ${{github.workspace}}/build/fpga-sv-template-out.tar.gz

      - name: 'Configure GitHub Pages'
        uses: actions/configure-pages@v5

      - name: 'Upload mdBook to GitHub Pages'
        id: github-pages-artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/out/doc/book'

  github-pages-deployment:
    needs: build
    runs-on: ubuntu-26.04
    environment:
      name: github-pages
      url: ${{ steps.github-pages-artefact.outputs.page_url }}
    steps:
      - name: 'Deploy mdBook to GitHub Pages'
        id: github-pages-artefact
        uses: actions/deploy-pages@v5
