name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "build/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-26.04
    env:
      TOOLS: "${{github.workspace}}/build/tools"
      PIPX_HOME: "${{github.workspace}}/build/tools/python"
      PIPX_BIN_DIR: "${{github.workspace}}/build/tools/python/bin"
    steps:
      - uses: actions/checkout@v5

      - name: 'Tooling: Install Tools from Distribution'
        run: |
          set -e;
          sudo apt-get -q -y update;
          sudo apt-get -q -y install \
            cmake \
            curl \
            fpga-icestorm \
            git \
            gperf \
            haskell-stack \
            iverilog \
            libboost-dev \
            libboost-program-options-dev \
            libboost-iostreams-dev \
            pipx \
            rsync \
            yosys \
            yosys-abc;

          npm install -g --ignore-scripts wavedrom;

      - name: 'Tooling: Restore from Cache'
        id: cache-build-tools-restore
        uses: actions/cache/restore@v6
        with:
          path: ${{github.workspace}}/build/tools
          key: ${{runner.os}}-build-tools

      - name: 'Tooling: Download and Install SBY'
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        run: |
          set -e;
          mkdir -p "${TOOLS}" && pushd "${TOOLS}";

          git clone https://github.com/SRI-CSL/yices2.git;
          pushd yices2;
          autoconf;
          ./configure;
          make && sudo make install;
          popd;

          git clone https://github.com/YosysHQ/sby.git;
          pushd sby && sudo make install && popd;

          popd;

      - name: 'Tooling: Install SBY from Cached Builds'
        if: steps.cache-build-tools-restore.outputs.cache-hit == 'true'
        run: |
          set -e;
          mkdir -p "${TOOLS}" && pushd "${TOOLS}";

          pushd yices2;
          sudo make install;
          popd;

          pushd sby && sudo make install && popd;

          popd;

      - name: 'Tooling: Download and Install Project Apicula (Gowin FPGAs)'
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        run: |
          set -e;
          mkdir -p "${PIPX_HOME}" && pushd "${PIPX_HOME}";

          pipx install --force apycula;

          popd;

      - name: 'Tooling: Download and Install SV2V'
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        run: |
          set -e;
          pushd "${TOOLS}";

          git clone https://github.com/zachjs/sv2v.git;
          pushd sv2v && make && popd;

          popd;

      - name: 'Tooling: Download, Build and Install nextpnr'
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        run: |
          set -e;
          pushd "${TOOLS}";

          git clone https://github.com/YosysHQ/nextpnr.git;
          git clone https://github.com/f4pga/prjxray-db.git;

          mkdir -p nextpnr/build && pushd nextpnr/build;
          cmake .. \
            -DARCH="ice40;himbaechel" \
            -DHIMBAECHEL_UARCH="gowin;xilinx" \
            -DICESTORM_INSTALL_PREFIX=/usr \
            -DHIMBAECHEL_PRJXRAY_DB="${TOOLS}/prjxray-db" \
            -DCMAKE_INSTALL_PREFIX="${TOOLS}/nextpnr/bin";

          make -j$(nproc) && make install;
          popd;

          popd;

      - name: 'Tooling: Download and Install mdBook'
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        run: |
          set -e;
          pushd "${TOOLS}";

          mkdir -p mdbook;
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.5.3/mdbook-v0.5.3-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=mdbook;

          popd;

      - name: 'Tooling: Store in Cache'
        id: cache-build-tools-store
        if: steps.cache-build-tools-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v6
        with:
          path: ${{github.workspace}}/build/tools
          key: ${{steps.cache-build-tools-restore.outputs.cache-primary-key}}

      - name: 'Test, Synthesise, Place-and-Route, Pack Bitstream and Generate Documentation'
        run: |
          set -e;
          MAKE="make all SV2V=\"${TOOLS}/sv2v/bin/sv2v\" NEXTPNR_PREFIX="${TOOLS}/nextpnr/bin/" GOWIN_PACK=\"${PIPX_BIN_DIR}/gowin_pack\" MDBOOK=\"${TOOLS}/mdbook/mdbook\"";
          pushd "${GITHUB_WORKSPACE}/build";
          make --version;
          ${MAKE} SYNTH_TARGET=ice40up5k PNR_PACKAGE=sg48;
          ${MAKE} SYNTH_TARGET=ice40hx1k PNR_PACKAGE=tq144;

          ${MAKE} SYNTH_TARGET=gw2alv18 PNR_PACKAGE=pg256 GOWIN_SPEED_GRADE=C8/I7;
          popd;

      - name: 'Bundle Artefacts'
        if: always()
        run: |
          set -e;
          pushd "${GITHUB_WORKSPACE}/build";
          GZIP_OPT=-9 tar -cz out > fpga-sv-template-out.tar.gz;
          popd;

      - name: 'Store Artefacts'
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: fpga-sv-template-out
          if-no-files-found: error
          archive: false
          path: ${{github.workspace}}/build/fpga-sv-template-out.tar.gz

      - name: 'Configure GitHub Pages'
        uses: actions/configure-pages@v5

      - name: 'Upload mdBook to GitHub Pages'
        id: github-pages-artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/out/doc/book'

  github-pages-deployment:
    needs: build
    runs-on: ubuntu-26.04
    environment:
      name: github-pages
      url: ${{ steps.github-pages-artefact.outputs.page_url }}
    steps:
      - name: 'Deploy mdBook to GitHub Pages'
        id: github-pages-artefact
        uses: actions/deploy-pages@v5
